### ISSUE TITLE
Error Chanels and replay, but not Movies and Recordings

### ISSUE THREAD

**Issue by F1reP0wer12345** [tgiesela/repository.ziggotv#1]
I've been using your addon for over a month now. Not very frequently, but about a week ago it started giving me either the error on the attached photo, or a blank error, when trying to play channels, or replaying certain shows from the EPG. I don't really understand the error myself, because why would I be requiring a WiFi connection, if that's what I'm using. When I first used the addon I was connected through ethernet, and also using a different device. Both don't work anymore and give me this error. Does this also happen when you use this addon? Can you help me fix it? I'm using LibreElec and Kodi for Windows. The Kodi for Windows logs are in the url below:
https://paste.kodi.tv/hofoyilizu.kodi
The only two relevent lines are below:
2024-05-05 21:25:49.727 T:17212   error <general>: HTTPRequestHandler log_request(403,-)
2024-05-05 21:25:49.770 T:16144   error <general>: Webexception in play_epg: Unexpected response status in dynamic_call: 403
![IMG_20240505_210948_242~2](https://github.com/tgiesela/repository.ziggotv/assets/74012332/af4944b2-a216-4d26-97fc-4cb0be0e8a7b)

**Comment by tgiesela** [comment]
Does this happen for all channels or only specific ones? And only when playing from EPG?
The http status-code is 403, which may indicate lack of authorization. Are you using the addon on different machines at the same time or use the web-interface while playing? There is a limit on the number of simultaneous streams and exceeding that limit may cause some weird errors.
I am currently using Kodi 21 on Windows and Kodi 20 on LibreElec. Both work without issues, although I have not tested all channels of course.
If the problem persists, please create a debug log to provide me more information for investigating the problem.

**Comment by F1reP0wer12345** [comment]
I guess it's possible I've signed in to my account on my laptop through ziggogo.tv, but there's currently nothing playing. The issue started about a week ago, and has persisted ever since. I've also not tried all channels, but when i got the error I switched to NPO 1, 2 & 3 all of which receiving the same error. I will post parts of the debug logs below. I didn't share all of it because I'm not sure how much sensitive information (like password, etc.) is in there. Here are the logs:
https://paste.kodi.tv/axifizinov.kodi

**Comment by tgiesela** [comment]
I think something within your configuration is messed up. Things you can try:

1. check your credentials in the settings. If the problem persists, 
2. remove the **session.json** file of the ziggo addon ('Kodi\userdata\addon_data\plugin.video.ziggotv\') and restart Kodi. If the problem persists
3. remove all addon data of the ziggo addon ('Kodi\userdata\addon_data\plugin.video.ziggotv\') and restart Kodi. If the problem persists
4. uninstall the addon and erase all settings and reinstall the addon. 

If that still does not solve the problem, please enable the debug option to trace all http traffic and then submit the part of kodi.log that starts with 'HTTP GET Request received: /function/obtain_tv_streaming_token' and ends with 'HTTP GET Request processed: /function/obtain_tv_streaming_token'. You can erase the ACCESSTOKEN/CLAIMSTOKEN parts for security reasons.

**Comment by F1reP0wer12345** [comment]
I've tried all of them with no result. Where is this option that logs http traffic?

**Comment by tgiesela** [comment]
It is in the settings of the addon. Select the 'Options' button on the left and enable 'Trace Network Traffic' and 'print request content' and 'print response content'.
I think there is an authorization issue. Can you also check if you can play ziggo channels via the browser ([ziggogo](https://www.ziggogo.tv/)) with the same user credentials and profile you use in the Kodi addon?

**Comment by F1reP0wer12345** [comment]
You mean this part right here?:
```
2024-05-06 21:58:07.403 T:12172   debug <general>: HTTP GET Request received: /function/obtain_tv_streaming_token?args={"channelId":+"NL_000003_019405",+"assetType":+"Orion-DASH-HEVC"}
2024-05-06 21:58:07.486 T:12172   error <general>: HTTPRequestHandler log_request(403,-)
2024-05-06 21:58:07.487 T:12172   debug <general>: HTTP GET Request processed: /function/obtain_tv_streaming_token?args={"channelId":+"NL_000003_019405",+"assetType":+"Orion-DASH-HEVC"}
```
I can still watch movies & series, replay and recordings, which should not be possible if it can't authenticate, can it? Or are they not using the same authentication? Because I can replay a TV show, I can just replay the latest from a channel and fast forward to the live part, as a temporary workaround. This is only possible on my windows computer right now (Running Kodi v20.3 in case your wondering). However my Libreelec computer can't stream anything right now. I will attempt to 'remove all addon data of the ziggo addon' and sign back in tomorrow.

**Comment by tgiesela** [comment]
It is definitely not an authentication error, your user-id/password are ok. But is may be an authorization error. The live channels are played in full-HD. All the others are just HD. I can see from the URL that is trying to play full-HD. What you can do is limit playback to HD. You can do that in the settings of the ziggo addon:

> Add-ons > my add-ons > Video add-ons > Ziggo TV > Configure > Options > Full-HD set to off.

**Comment by F1reP0wer12345** [comment]
I'm currently not home so I can't change those options, but I did try something else. With my laptop I created a virtual machine for LibreElec and added this addon to Kodi. With no changes to the settings, it just straight up worked. I checked in the settings if perhaps Full-HD was off by default, but it wasn't. When I turn it off it still works. I am however on a different network compared to my home network. This still doesnt explain the error though, so when I return home tomorrow, I will check if it still doesn't work on my PC, and if so, disable the Full-HD. Thank you for the help so far.

**Comment by F1reP0wer12345** [comment]
I've disabled the Full-HD option, and now it does work. I can watch all channels again. However the quality isn't perfect, especially on my TV. Why is it that disabling the Full-HD option fixes the issue? What's so different about the authorization with Full-HD on, and Full-HD off?

**Comment by tgiesela** [comment]
Now I am just going to do some guessing because I don't know either. 

If you look at the original error message it mentions that you should be connected to 'your Wifi Network'. That sounds strange, but maybe Ziggo wants you to be connected to their own network (not specific Wifi of course). I know nothing about your network setup, but I can imagine that you have another Internet provider than Ziggo. And in that case they may not allow you to watch in full-HD. 
Another issue might be the type of your subscription to Ziggo. Don't know if that is possible, but maybe that can disallow full-HD. Although I have a simple subscription I can watch full-HD.  And I also have Internet from Ziggo.

Like I said: it is just a wild guess....

**Comment by F1reP0wer12345** [comment]
I'm currently living in an appartment with KPN as provider. I'm using Ziggo Go from my parents. But since Ziggo and KPN are basically rivals, I can understand Ziggo would block things like that on a different internet provider. I still have that Virtual Machine on my laptop. Assuming you're right, it would show that same error if I use it at home. I will check that soon. Would it be possible to trick your addon into thinking it's on a Ziggo network instead of KPN? Could the add-on proxy settings be used? Or what is the proxies purpose?

**Comment by tgiesela** [comment]
It is not the addon that checks if it is on a Ziggo network. It is the Ziggo-server which detects if the client is on a different network. So this not possible. Maybe a VPN might help you.

**Comment by F1reP0wer12345** [comment]
I don't think you can choose a VPN that is has Ziggo as it's ISP, but thank you for explaining what's causing this issue. Although not in Full-HD, I'm glad I can still watch my favorite channels.
